In [19]:
import numpy as np

In [20]:
arr = [1,2,3,4,5,6]

In [23]:
arr1 = np.array(arr)

In [24]:
arr1 + arr1

array([ 2,  4,  6,  8, 10, 12])

In [25]:
arr1 + 1

array([2, 3, 4, 5, 6, 7])

In [27]:
arry = np.arange(0,25)

In [28]:
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arry_d = arry.reshape(5,5)

In [33]:
arry_d.shape

(5, 5)

In [34]:
arry_d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arry_d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [36]:
arry_d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

In [37]:
arry_d.sum(axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [38]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])  

In [39]:
account_total = account_transactions.sum()

In [40]:
account_total

2720