In [4]:
import numpy as np

In [5]:
my_list = [1,2,3,4]

In [6]:
type(my_list)

list

In [7]:
np.array(my_list)

array([1, 2, 3, 4])

In [8]:
myarry = np.array(my_list)

In [9]:
myarry

array([1, 2, 3, 4])

In [10]:
type(myarry)

numpy.ndarray

In [11]:
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
mymtrix = np.array(my_matrix)

In [17]:
mymtrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(5,40,1.5)

array([ 5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. , 15.5, 17. , 18.5, 20. ,
       21.5, 23. , 24.5, 26. , 27.5, 29. , 30.5, 32. , 33.5, 35. , 36.5,
       38. , 39.5])

In [28]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.zeros(2)

array([0., 0.])

In [30]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.linspace(2,24,3)

array([ 2., 13., 24.])

In [32]:
np.linspace(1,14,4)

array([ 1.        ,  5.33333333,  9.66666667, 14.        ])

In [33]:
np.linspace(2,24,8)

array([ 2.        ,  5.14285714,  8.28571429, 11.42857143, 14.57142857,
       17.71428571, 20.85714286, 24.        ])

In [36]:
len(np.linspace(2,24,8))

8

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.eye(4,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [41]:
np.random.rand(3)

array([0.07027351, 0.22887945, 0.93451313])

In [96]:
a = np.random.rand(4,9)

In [97]:
a

array([[0.73688738, 0.86638985, 0.23075412, 0.10550225, 0.74293527,
        0.47515634, 0.75965283, 0.48599313, 0.27593379],
       [0.38178337, 0.6762014 , 0.73647103, 0.9706047 , 0.68136272,
        0.490452  , 0.12840324, 0.50383093, 0.4096691 ],
       [0.25559738, 0.61806603, 0.89501445, 0.66750239, 0.57585336,
        0.64872048, 0.96107677, 0.86436925, 0.78272878],
       [0.31110332, 0.27191386, 0.95738054, 0.51644268, 0.41742553,
        0.63886307, 0.68952736, 0.76848649, 0.44285459]])

In [95]:
np.random.rand(50)

array([0.12144377, 0.89100806, 0.51509223, 0.92441901, 0.58124263,
       0.77325639, 0.42267689, 0.82546475, 0.38540456, 0.35434596,
       0.42807852, 0.39506518, 0.84462971, 0.37382381, 0.37158098,
       0.41594296, 0.42454448, 0.66280484, 0.18977593, 0.72247865,
       0.25366097, 0.96267414, 0.13266125, 0.8067967 , 0.35499545,
       0.0846383 , 0.73116878, 0.99660085, 0.00959277, 0.23757339,
       0.46192478, 0.76525884, 0.97250331, 0.915947  , 0.58744678,
       0.44437533, 0.44107594, 0.69399137, 0.72664097, 0.73473276,
       0.38422053, 0.94539591, 0.79366926, 0.25781467, 0.63648694,
       0.84514052, 0.00777515, 0.07703627, 0.98942514, 0.79096501])

In [52]:
np.random.randn(8)

array([ 0.73578494, -0.61740936,  1.36415339,  0.28252078, -1.40794657,
       -0.2619311 , -1.14357218, -1.95958012])

In [63]:
np.random.randn(200)

array([ 0.12383134,  0.33041733, -1.00143028,  1.88367842,  0.22983308,
       -1.06242943,  1.90846433,  1.64744035,  0.47433736,  0.45228957,
       -0.5001927 ,  0.34532523,  0.79584917,  0.74965782,  0.4333172 ,
       -1.19709288, -1.59671766,  1.3168491 ,  0.224065  ,  0.25267995,
        1.45854123, -0.38452911, -1.00182875,  0.93810558, -0.73316065,
       -1.67105075,  0.73869059,  0.70247164, -0.58945635,  0.20912194,
       -0.9758187 ,  2.23063158, -1.04572173,  0.9598104 ,  1.11688286,
       -0.31296429,  1.92481748,  2.40773413, -0.05379033,  1.95558482,
        0.06833152,  0.39509313,  0.30484036,  0.42914391, -0.48033556,
        1.5478576 , -0.04618184,  0.24113297,  1.127451  ,  0.69054496,
        0.70185795,  0.19047268, -1.69372178,  0.34563641, -0.53012699,
        0.48354396, -2.2227941 , -0.34716842, -0.63864834,  1.56244044,
       -0.25485254,  0.22647304, -0.11595207,  0.87701049, -0.8769477 ,
       -1.5639909 ,  0.60498183,  1.45380332, -0.15571987,  0.43

In [59]:
np.random.randint(2,14,(5,4))

array([[ 6, 11, 11, 12],
       [ 9,  8, 12,  2],
       [ 2,  3,  8, 11],
       [ 3, 13,  7,  8],
       [ 6,  6,  3,  6]])

In [67]:
np.random.seed(20)
np.random.rand(5)

array([0.5881308 , 0.89771373, 0.89153073, 0.81583748, 0.03588959])

In [68]:
np.random.rand(5)

array([0.69175758, 0.37868094, 0.51851095, 0.65795147, 0.19385022])

In [69]:
np.random.rand(5)

array([0.2723164 , 0.71860593, 0.78300361, 0.85032764, 0.77524489])

In [71]:
np.random.seed(20)
np.random.rand(6)

array([0.5881308 , 0.89771373, 0.89153073, 0.81583748, 0.03588959,
       0.69175758])

In [72]:
arr = np.arange(0,30)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [75]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [82]:
nrarry = np.random.randint(0,100,20)

In [86]:
nrarry

array([40, 85, 90, 26, 83, 16, 62, 16,  7, 98,  6, 26, 13, 75, 58, 25,  3,
       74, 75, 61])

In [87]:
nrarry.max()

98

In [88]:
nrarry.min()

3

In [89]:
nrarry.argmax()

9

In [91]:
nrarry.argmin()

16

In [90]:
sorted(nrarry)

[3, 6, 7, 13, 16, 16, 25, 26, 26, 40, 58, 61, 62, 74, 75, 75, 83, 85, 90, 98]

In [92]:
nrarry.dtype

dtype('int32')

In [98]:
a.dtype

dtype('float64')

In [99]:
b = np.random.rand(2,6)

In [100]:
b

array([[0.95131449, 0.53279129, 0.31356138, 0.20352206, 0.98534762,
        0.46783921],
       [0.70292922, 0.15460409, 0.73099939, 0.66058604, 0.73642868,
        0.90668929]])

In [101]:
b.dtype

dtype('float64')

In [102]:
# TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.

In [109]:
myarray = np.linspace(0,101,10)

In [110]:
myarray

array([  0.        ,  11.22222222,  22.44444444,  33.66666667,
        44.88888889,  56.11111111,  67.33333333,  78.55555556,
        89.77777778, 101.        ])