In [1]:
import numpy as np

In [4]:
arry = np.arange(0,10)

In [5]:
arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arry[:5]

array([0, 1, 2, 3, 4])

In [7]:
arry[:5] = 11

# python da bu işleme izin vermiyor.

In [8]:
arry

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9])

In [9]:
arry = np.arange(0,10)

In [10]:
arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arry[:] = 99

In [12]:
arry

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [13]:
arry_2d = [[5,10,15],[20,25,30],[35,40,45]]

In [15]:
arry_2d = np.array(arry_2d)

In [16]:
arry_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arry_2d[0]

array([ 5, 10, 15])

In [18]:
np.shape(arry_2d)

(3, 3)

In [19]:
np.shape(arry_2d)[0]

3

In [20]:
arry_2d.

(3, 3)

In [21]:
arry_2d.array

AttributeError: 'numpy.ndarray' object has no attribute 'array'

In [22]:
arry_2d[1]

array([20, 25, 30])

In [23]:
arry_2d[1,1]

25

In [24]:
arry_2d[1][1] = 24

In [25]:
arry_2d

array([[ 5, 10, 15],
       [20, 24, 30],
       [35, 40, 45]])

In [28]:
arry_2d[:2,:2]

array([[ 5, 10],
       [20, 24]])

In [29]:
arr = np.arange(0,11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [32]:
narr = arr>4

In [36]:
arr[narr]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
narr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [38]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [42]:
# TASK: Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.
# NOTE: Many different ways to do this! Your final answer should be an integer.

In [58]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [63]:
dice_rolls
dice_rolls.dtype

dtype('int32')

In [64]:
#ice_rolls>2

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [66]:
dice_rolls[dice_rolls>2]

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [67]:
len(dice_rolls)

29